#!/bin/sh

var = ( php7.4-{curl,xml,fpm,bcmath,bz2,intl,gd,mbstring,mysql,zip,common} ) 

sudo apt install -y php7.4
sudo apt install -y "${var[@]}"

sudo apt install -y nginx

cd ~
curl -sS https://getcomposer.org/installer -o composer-setup.php
HASH=`curl -sS https://composer.github.io/installer.sig`
echo $HASH
php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
composer
